# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKT40QtU8FL7YxO6Eyo2zeYvAgJxHVJ3

## Visualisations using Streamlit

Streamlit is an open source python library to create custom web apps.
Streamlit code needs to be executed as a separate python script to view the Streamlit app on a browser.
page = st.sidebar.selectbox('Select the visualisation to view',('No-Show rate by Diagnosis','No-Show rate by Age group','No-Show rate by Gender','Diagnosis based on Gender','Age group distribution'))
"""

import streamlit as st
import streamlit.components.v1 as components

st.image("HEU.jpg")
st.header('Visualisations for HEU')

st.sidebar.title('HEU data analysis')
view = st.sidebar.radio('Select the visualisation to view',('No-Show rate by Diagnosis','No-Show rate by Age group','No-Show rate by Gender','Diagnosis based on Gender','Age group distribution','SQL Database design'))


if view == 'No-Show rate by Diagnosis':
    st.image("noshowDiagnosis.jpg")
    st.markdown("***Analysis:*** The population affected by Asthma has more no-show rates compared to the population suffering from Diabetes and Hypertension.")
    
if view == 'No-Show rate by Age group':
    st.image("noshowage.jpg")
    st.markdown("***Analysis:*** The 19-35 age group exhibits the highest no-show rate, likely due to lower health concerns at a younger age. Additionally, individuals aged 66+ may face mobility challenges, contributing to a 50% no-show rate.")

if view == 'No-Show rate by Gender':
    st.image("noshowgender.jpg")
    st.markdown("***Analysis:***. Males have a higher no-show rate compared to females, possibly due to differences in health-seeking behavior and prioritisation of medical appointments.")

if view == 'Diagnosis based on Gender':
    st.image("Diagnosisbygender.jpg")
    st.markdown("***Analysis:*** Males have slightly higher cases of Asthma and Diabetes, while females show a significantly higher count for Hypertension. This suggests potential gender-based differences in health conditions.")

if view == 'Age group distribution':
    st.image("agedistribution.jpg")
    st.markdown("***Analysis:*** The histogram displays the age distribution of a population, with frequencies varying across different age groups. Peaks around ages 45-50 and 75-80 suggest higher concentrations in these ranges.")

if view == 'SQL Database design':
    st.image("sql.jpg")

    
