# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKT40QtU8FL7YxO6Eyo2zeYvAgJxHVJ3

## Visualisations using Streamlit

Streamlit is an open source python library to create custom web apps.
Streamlit code is integrated in the main notebook; however, it needs to be executed as a separate python script to view the Streamlit app on a browser. I have therefore created a separate Visualisation notebook.
"""

import streamlit as st
import streamlit.components.v1 as components

st.title('Visualisations for Health Economics Unit')
st.image("noshowDiagnosis.jpg", caption="Noshow results based on Diagnosis")

st.sidebar.title('Choose the Visualisation')
option1=st.sidebar.selectbox('Select the graph',('No-Show rate by Diagnosis','No-Show rate by Age group','No-show rate by Gender','Diagnosis based on Gender','Age group distribution','Distribution by Appointments over time'))


if option1=='No-Show rate by Diagnosis':
    HtmlFilesyn = open("noshowDiagnosis.html",'r',encoding='utf-8')
    source_code = HtmlFilesyn.read()
    components.html(source_code, height = 600, width = 700)
    
